import socket

HOST = socket.gethostbyname(socket.gethostname())
CLIENT_PORT = 9990
CLIENT_ADDR = (HOST,CLIENT_PORT)
LOCAL_PORT = 9991
LOCAL_ADDR = (HOST,LOCAL_PORT)
AUTH_PORT = 9992
AUTH_ADDR = (HOST,AUTH_PORT)
TLD_PORT = 9993
TLD_ADDR = (HOST,TLD_PORT)
ROOT_PORT = 9994
ROOT_ADDR = (HOST,ROOT_PORT)